--------------------------------------------------------
--  DDL for Package FIDE_PROYECTO_FINAL_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO1"."FIDE_PROYECTO_FINAL_PKG" AS
--1. TABLA ESTADOS
--1. TABLA ESTADOS
--1. TABLA ESTADOS
PROCEDURE SP_FIDE_ESTADOS_INSERT (
    P_ID_ESTADO   IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE      IN FIDE_ESTADOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_ESTADOS_TB.DESCRIPCION%TYPE
);
PROCEDURE SP_FIDE_ESTADOS_UPDATE (
    P_ID_ESTADO   IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE      IN FIDE_ESTADOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_ESTADOS_TB.DESCRIPCION%TYPE
);
--2. TABLA CLIENTES
--2. TABLA CLIENTES
--2. TABLA CLIENTES
PROCEDURE SP_FIDE_CLIENTES_INSERT (
    P_ID_CLIENTE       IN FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
    P_NOMBRE           IN FIDE_CLIENTES_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
    P_ID_ESTADO        IN FIDE_CLIENTES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CLIENTES_UPDATE (
    P_ID_CLIENTE       IN FIDE_CLIENTES_TB.ID_CLIENTE%TYPE,
    P_NOMBRE           IN FIDE_CLIENTES_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
    P_ID_ESTADO        IN FIDE_CLIENTES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CLIENTES_DELETE (
    P_ID_CLIENTE       IN FIDE_CLIENTES_TB.ID_CLIENTE%TYPE
);

--3. TABLA TELEFONOS
--3. TABLA TELEFONOS
--3. TABLA TELEFONOS
PROCEDURE SP_FIDE_TELEFONOS_INSERT (
    P_ID_CLIENTE IN FIDE_TELEFONOS_TB.ID_CLIENTE%TYPE,
    P_TELEFONO   IN FIDE_TELEFONOS_TB.TELEFONO%TYPE,
    P_TIPO       IN FIDE_TELEFONOS_TB.TIPO%TYPE,
    P_ID_ESTADO  IN FIDE_TELEFONOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TELEFONOS_UPDATE (
    P_ID_CLIENTE IN FIDE_TELEFONOS_TB.ID_CLIENTE%TYPE,
    P_TELEFONO   IN FIDE_TELEFONOS_TB.TELEFONO%TYPE,
    P_TIPO       IN FIDE_TELEFONOS_TB.TIPO%TYPE,
    P_ID_ESTADO  IN FIDE_TELEFONOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TELEFONOS_DELETE (
    P_ID_CLIENTE IN FIDE_TELEFONOS_TB.ID_CLIENTE%TYPE,
    P_TELEFONO   IN FIDE_TELEFONOS_TB.TELEFONO%TYPE
);

--4. TABLA CORREOS
--4. TABLA CORREOS
--4. TABLA CORREOS
PROCEDURE SP_FIDE_CORREOS_INSERT (
    P_ID_CLIENTE IN FIDE_CORREOS_TB.ID_CLIENTE%TYPE,
    P_CORREO     IN FIDE_CORREOS_TB.CORREO%TYPE,
    P_TIPO       IN FIDE_CORREOS_TB.TIPO%TYPE,
    P_ID_ESTADO  IN FIDE_CORREOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CORREOS_UPDATE (
    P_ID_CLIENTE IN FIDE_CORREOS_TB.ID_CLIENTE%TYPE,
    P_CORREO     IN FIDE_CORREOS_TB.CORREO%TYPE,
    P_TIPO       IN FIDE_CORREOS_TB.TIPO%TYPE,
    P_ID_ESTADO  IN FIDE_CORREOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CORREOS_DELETE (
    P_ID_CLIENTE IN FIDE_CORREOS_TB.ID_CLIENTE%TYPE,
    P_CORREO     IN FIDE_CORREOS_TB.CORREO%TYPE
);

--5. TABLA PROVINCIAS
--5. TABLA PROVINCIAS
--5. TABLA PROVINCIAS
PROCEDURE SP_FIDE_PROVINCIAS_INSERT (
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE,
    P_NOMBRE       IN FIDE_PROVINCIAS_TB.NOMBRE%TYPE,
    P_ID_ESTADO    IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PROVINCIAS_UPDATE (
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE,
    P_NOMBRE       IN FIDE_PROVINCIAS_TB.NOMBRE%TYPE,
    P_ID_ESTADO    IN FIDE_PROVINCIAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PROVINCIAS_DELETE (
    P_ID_PROVINCIA IN FIDE_PROVINCIAS_TB.ID_PROVINCIA%TYPE
);

--6. TABLA CANTONES
--6. TABLA CANTONES
--6. TABLA CANTONES
PROCEDURE SP_FIDE_CANTONES_INSERT (
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE,
    P_NOMBRE    IN FIDE_CANTONES_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CANTONES_UPDATE (
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE,
    P_NOMBRE    IN FIDE_CANTONES_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN FIDE_CANTONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CANTONES_DELETE (
    P_ID_CANTON IN FIDE_CANTONES_TB.ID_CANTON%TYPE
);

--7. TABLA DISTRITOS
--7. TABLA DISTRITOS
--7. TABLA DISTRITOS
PROCEDURE SP_FIDE_DISTRITOS_INSERT (
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE,
    P_NOMBRE      IN FIDE_DISTRITOS_TB.NOMBRE%TYPE,
    P_ID_ESTADO   IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_DISTRITOS_UPDATE (
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE,
    P_NOMBRE      IN FIDE_DISTRITOS_TB.NOMBRE%TYPE,
    P_ID_ESTADO   IN FIDE_DISTRITOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_DISTRITOS_DELETE (
    P_ID_DISTRITO IN FIDE_DISTRITOS_TB.ID_DISTRITO%TYPE
);

--8. TABLA DIRECCIONES
--8. TABLA DIRECCIONES
--8. TABLA DIRECCIONES
PROCEDURE SP_FIDE_DIRECCIONES_INSERT (
    P_ID_CLIENTE   IN FIDE_DIRECCIONES_TB.ID_CLIENTE%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCIONES_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON    IN FIDE_DIRECCIONES_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO  IN FIDE_DIRECCIONES_TB.ID_DISTRITO%TYPE,
    P_ID_ESTADO    IN FIDE_DIRECCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_DIRECCIONES_UPDATE (
    P_ID_CLIENTE   IN FIDE_DIRECCIONES_TB.ID_CLIENTE%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCIONES_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON    IN FIDE_DIRECCIONES_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO  IN FIDE_DIRECCIONES_TB.ID_DISTRITO%TYPE,
    P_ID_ESTADO    IN FIDE_DIRECCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_DIRECCIONES_DELETE (
    P_ID_CLIENTE   IN FIDE_DIRECCIONES_TB.ID_CLIENTE%TYPE,
    P_ID_PROVINCIA IN FIDE_DIRECCIONES_TB.ID_PROVINCIA%TYPE,
    P_ID_CANTON    IN FIDE_DIRECCIONES_TB.ID_CANTON%TYPE,
    P_ID_DISTRITO  IN FIDE_DIRECCIONES_TB.ID_DISTRITO%TYPE
);

--9. TABLA PUESTOS
--9. TABLA PUESTOS
--9. TABLA PUESTOS
PROCEDURE SP_FIDE_PUESTOS_INSERT (
    P_ID_PUESTO   IN FIDE_PUESTOS_TB.ID_PUESTO%TYPE,
    P_NOMBRE      IN FIDE_PUESTOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_PUESTOS_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO   IN FIDE_PUESTOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PUESTOS_UPDATE (
    P_ID_PUESTO   IN FIDE_PUESTOS_TB.ID_PUESTO%TYPE,
    P_NOMBRE      IN FIDE_PUESTOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_PUESTOS_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO   IN FIDE_PUESTOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PUESTOS_DELETE (
    P_ID_PUESTO IN FIDE_PUESTOS_TB.ID_PUESTO%TYPE
);

--10. TABLA EMPLEADOS
--10. TABLA EMPLEADOS
--10. TABLA EMPLEADOS
PROCEDURE SP_FIDE_EMPLEADOS_INSERT (
    P_ID_EMPLEADO       IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_NOMBRE           IN FIDE_EMPLEADOS_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_MATERNO%TYPE,
    P_ID_PUESTO        IN FIDE_EMPLEADOS_TB.ID_PUESTO%TYPE,
    P_ID_ESTADO        IN FIDE_EMPLEADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_EMPLEADOS_UPDATE (
    P_ID_EMPLEADO       IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_NOMBRE           IN FIDE_EMPLEADOS_TB.NOMBRE%TYPE,
    P_APELLIDO_PATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN FIDE_EMPLEADOS_TB.APELLIDO_MATERNO%TYPE,
    P_ID_PUESTO        IN FIDE_EMPLEADOS_TB.ID_PUESTO%TYPE,
    P_ID_ESTADO        IN FIDE_EMPLEADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_EMPLEADOS_DELETE (
    P_ID_EMPLEADO IN FIDE_EMPLEADOS_TB.ID_EMPLEADO%TYPE
);

--11. TABLA TELEFONOS DE EMPLEADOS
--11. TABLA TELEFONOS DE EMPLEADOS
--11. TABLA TELEFONOS DE EMPLEADOS
PROCEDURE SP_FIDE_TELEFONOS_EMPLEADOS_INSERT (
    P_ID_EMPLEADO IN FIDE_TELEFONOS_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_TELEFONO    IN FIDE_TELEFONOS_EMPLEADOS_TB.TELEFONO%TYPE,
    P_TIPO        IN FIDE_TELEFONOS_EMPLEADOS_TB.TIPO%TYPE,
    P_ID_ESTADO   IN FIDE_TELEFONOS_EMPLEADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TELEFONOS_EMPLEADOS_UPDATE (
    P_ID_EMPLEADO IN FIDE_TELEFONOS_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_TELEFONO    IN FIDE_TELEFONOS_EMPLEADOS_TB.TELEFONO%TYPE,
    P_TIPO        IN FIDE_TELEFONOS_EMPLEADOS_TB.TIPO%TYPE,
    P_ID_ESTADO   IN FIDE_TELEFONOS_EMPLEADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TELEFONOS_EMPLEADOS_DELETE (
    P_ID_EMPLEADO IN FIDE_TELEFONOS_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_TELEFONO    IN FIDE_TELEFONOS_EMPLEADOS_TB.TELEFONO%TYPE
);

--12. TABLA CORREOS DE EMPLEADOS
--12. TABLA CORREOS DE EMPLEADOS
--12. TABLA CORREOS DE EMPLEADOS
PROCEDURE SP_FIDE_CORREOS_EMPLEADOS_INSERT (
    P_ID_EMPLEADO IN FIDE_CORREOS_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_CORREO      IN FIDE_CORREOS_EMPLEADOS_TB.CORREO%TYPE,
    P_TIPO        IN FIDE_CORREOS_EMPLEADOS_TB.TIPO%TYPE,
    P_ID_ESTADO   IN FIDE_CORREOS_EMPLEADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CORREOS_EMPLEADOS_UPDATE (
    P_ID_EMPLEADO IN FIDE_CORREOS_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_CORREO      IN FIDE_CORREOS_EMPLEADOS_TB.CORREO%TYPE,
    P_TIPO        IN FIDE_CORREOS_EMPLEADOS_TB.TIPO%TYPE,
    P_ID_ESTADO   IN FIDE_CORREOS_EMPLEADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CORREOS_EMPLEADOS_DELETE (
    P_ID_EMPLEADO IN FIDE_CORREOS_EMPLEADOS_TB.ID_EMPLEADO%TYPE,
    P_CORREO      IN FIDE_CORREOS_EMPLEADOS_TB.CORREO%TYPE
);

--13. TABLA ROLES
--13. TABLA ROLES
--13. TABLA ROLES
PROCEDURE SP_FIDE_ROLES_INSERT (
    P_ID_ROL      IN FIDE_ROLES_TB.ID_ROL%TYPE,
    P_NOMBRE      IN FIDE_ROLES_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_ROLES_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO   IN FIDE_ROLES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_ROLES_UPDATE (
    P_ID_ROL      IN FIDE_ROLES_TB.ID_ROL%TYPE,
    P_NOMBRE      IN FIDE_ROLES_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_ROLES_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO   IN FIDE_ROLES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_ROLES_DELETE (
    P_ID_ROL IN FIDE_ROLES_TB.ID_ROL%TYPE
);

--14. TABLA PERMISOS
--14. TABLA PERMISOS
--14. TABLA PERMISOS
PROCEDURE SP_FIDE_PERMISOS_INSERT (
    P_ID_PERMISO  IN FIDE_PERMISOS_TB.ID_PERMISO%TYPE,
    P_NOMBRE      IN FIDE_PERMISOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_PERMISOS_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO   IN FIDE_PERMISOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PERMISOS_UPDATE (
    P_ID_PERMISO  IN FIDE_PERMISOS_TB.ID_PERMISO%TYPE,
    P_NOMBRE      IN FIDE_PERMISOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION IN FIDE_PERMISOS_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO   IN FIDE_PERMISOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PERMISOS_DELETE (
    P_ID_PERMISO IN FIDE_PERMISOS_TB.ID_PERMISO%TYPE
);

--15. TABLA PERMISOS POR ROL
--15. TABLA PERMISOS POR ROL
--15. TABLA PERMISOS POR ROL
PROCEDURE SP_FIDE_PERMISOS_X_ROL_INSERT (
    P_ID_ROL     IN FIDE_PERMISOS_X_ROL_TB.ID_ROL%TYPE,
    P_ID_PERMISO IN FIDE_PERMISOS_X_ROL_TB.ID_PERMISO%TYPE,
    P_ID_ESTADO  IN FIDE_PERMISOS_X_ROL_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PERMISOS_X_ROL_UPDATE (
    P_ID_ROL     IN FIDE_PERMISOS_X_ROL_TB.ID_ROL%TYPE,
    P_ID_PERMISO IN FIDE_PERMISOS_X_ROL_TB.ID_PERMISO%TYPE,
    P_ID_ESTADO  IN FIDE_PERMISOS_X_ROL_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PERMISOS_X_ROL_DELETE (
    P_ID_ROL     IN FIDE_PERMISOS_X_ROL_TB.ID_ROL%TYPE,
    P_ID_PERMISO IN FIDE_PERMISOS_X_ROL_TB.ID_PERMISO%TYPE
);

--16. TABLA USUARIOS
--16. TABLA USUARIOS
--16. TABLA USUARIOS
PROCEDURE SP_FIDE_USUARIOS_INSERT (
    P_ID_USUARIO  IN FIDE_USUARIOS_TB.ID_USUARIO%TYPE,
    P_USUARIO     IN FIDE_USUARIOS_TB.USUARIO%TYPE,
    P_CONTRASENA  IN FIDE_USUARIOS_TB.CONTRASENA%TYPE,
    P_ID_EMPLEADO IN FIDE_USUARIOS_TB.ID_EMPLEADO%TYPE,
    P_ID_CLIENTE  IN FIDE_USUARIOS_TB.ID_CLIENTE%TYPE,
    P_ID_ROL      IN FIDE_USUARIOS_TB.ID_ROL%TYPE,
    P_ID_ESTADO   IN FIDE_USUARIOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_USUARIOS_UPDATE (
    P_ID_USUARIO  IN FIDE_USUARIOS_TB.ID_USUARIO%TYPE,
    P_USUARIO     IN FIDE_USUARIOS_TB.USUARIO%TYPE,
    P_CONTRASENA  IN FIDE_USUARIOS_TB.CONTRASENA%TYPE,
    P_ID_EMPLEADO IN FIDE_USUARIOS_TB.ID_EMPLEADO%TYPE,
    P_ID_CLIENTE  IN FIDE_USUARIOS_TB.ID_CLIENTE%TYPE,
    P_ID_ROL      IN FIDE_USUARIOS_TB.ID_ROL%TYPE,
    P_ID_ESTADO   IN FIDE_USUARIOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_USUARIOS_DELETE (
    P_ID_USUARIO IN FIDE_USUARIOS_TB.ID_USUARIO%TYPE
);

--17. TABLA REABASTECIMIENTO DE INVENTARIO
--17. TABLA REABASTECIMIENTO DE INVENTARIO
--17. TABLA REABASTECIMIENTO DE INVENTARIO
PROCEDURE SP_FIDE_REABASTECIMIENTO_INVENTARIO_INSERT (
    P_ID_REABASTECIMIENTO IN FIDE_REABASTECIMIENTO_INVENTARIO_TB.ID_REABASTECIMIENTO%TYPE,
    P_CANTIDAD            IN FIDE_REABASTECIMIENTO_INVENTARIO_TB.CANTIDAD%TYPE,
    P_ID_ESTADO           IN FIDE_REABASTECIMIENTO_INVENTARIO_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_REABASTECIMIENTO_INVENTARIO_UPDATE (
    P_ID_REABASTECIMIENTO IN FIDE_REABASTECIMIENTO_INVENTARIO_TB.ID_REABASTECIMIENTO%TYPE,
    P_CANTIDAD            IN FIDE_REABASTECIMIENTO_INVENTARIO_TB.CANTIDAD%TYPE,
    P_ID_ESTADO           IN FIDE_REABASTECIMIENTO_INVENTARIO_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_REABASTECIMIENTO_INVENTARIO_DELETE (
    P_ID_REABASTECIMIENTO IN FIDE_REABASTECIMIENTO_INVENTARIO_TB.ID_REABASTECIMIENTO%TYPE
);

--18. TABLA PROVEEDORES
--18. TABLA PROVEEDORES
--18. TABLA PROVEEDORES
PROCEDURE SP_FIDE_PROVEEDORES_INSERT (
    P_ID_PROVEEDOR        IN FIDE_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_NOMBRE              IN FIDE_PROVEEDORES_TB.NOMBRE%TYPE,
    P_ID_REABASTECIMIENTO IN FIDE_PROVEEDORES_TB.ID_REABASTECIMIENTO%TYPE,
    P_ID_ESTADO           IN FIDE_PROVEEDORES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PROVEEDORES_UPDATE (
    P_ID_PROVEEDOR        IN FIDE_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_NOMBRE              IN FIDE_PROVEEDORES_TB.NOMBRE%TYPE,
    P_ID_REABASTECIMIENTO IN FIDE_PROVEEDORES_TB.ID_REABASTECIMIENTO%TYPE,
    P_ID_ESTADO           IN FIDE_PROVEEDORES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PROVEEDORES_DELETE (
    P_ID_PROVEEDOR IN FIDE_PROVEEDORES_TB.ID_PROVEEDOR%TYPE
);

--19. TABLA TELEFONOS DE PROVEEDORES
--19. TABLA TELEFONOS DE PROVEEDORES
--19. TABLA TELEFONOS DE PROVEEDORES
PROCEDURE SP_FIDE_TELEFONOS_PROVEEDORES_INSERT (
    P_ID_PROVEEDOR IN FIDE_TELEFONOS_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_TELEFONO     IN FIDE_TELEFONOS_PROVEEDORES_TB.TELEFONO%TYPE,
    P_TIPO         IN FIDE_TELEFONOS_PROVEEDORES_TB.TIPO%TYPE,
    P_ID_ESTADO    IN FIDE_TELEFONOS_PROVEEDORES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TELEFONOS_PROVEEDORES_UPDATE (
    P_ID_PROVEEDOR IN FIDE_TELEFONOS_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_TELEFONO     IN FIDE_TELEFONOS_PROVEEDORES_TB.TELEFONO%TYPE,
    P_TIPO         IN FIDE_TELEFONOS_PROVEEDORES_TB.TIPO%TYPE,
    P_ID_ESTADO    IN FIDE_TELEFONOS_PROVEEDORES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TELEFONOS_PROVEEDORES_DELETE (
    P_ID_PROVEEDOR IN FIDE_TELEFONOS_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_TELEFONO     IN FIDE_TELEFONOS_PROVEEDORES_TB.TELEFONO%TYPE
);

--20. TABLA CORREOS DE PROVEEDORES
--20. TABLA CORREOS DE PROVEEDORES
--20. TABLA CORREOS DE PROVEEDORES
PROCEDURE SP_FIDE_CORREOS_PROVEEDORES_INSERT (
    P_ID_PROVEEDOR IN FIDE_CORREOS_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_CORREO       IN FIDE_CORREOS_PROVEEDORES_TB.CORREO%TYPE,
    P_TIPO         IN FIDE_CORREOS_PROVEEDORES_TB.TIPO%TYPE,
    P_ID_ESTADO    IN FIDE_CORREOS_PROVEEDORES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CORREOS_PROVEEDORES_UPDATE (
    P_ID_PROVEEDOR IN FIDE_CORREOS_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_CORREO       IN FIDE_CORREOS_PROVEEDORES_TB.CORREO%TYPE,
    P_TIPO         IN FIDE_CORREOS_PROVEEDORES_TB.TIPO%TYPE,
    P_ID_ESTADO    IN FIDE_CORREOS_PROVEEDORES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CORREOS_PROVEEDORES_DELETE (
    P_ID_PROVEEDOR IN FIDE_CORREOS_PROVEEDORES_TB.ID_PROVEEDOR%TYPE,
    P_CORREO       IN FIDE_CORREOS_PROVEEDORES_TB.CORREO%TYPE
);

--21. TABLA PRODUCTOS
--21. TABLA PRODUCTOS
--21. TABLA PRODUCTOS
PROCEDURE SP_FIDE_PRODUCTOS_INSERT (
    P_ID_PRODUCTO        IN FIDE_PRODUCTOS_TB.ID_PRODUCTO%TYPE,
    P_NOMBRE             IN FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION        IN FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
    P_PRECIO             IN FIDE_PRODUCTOS_TB.PRECIO%TYPE,
    P_UNIDADES_ACTUALES  IN FIDE_PRODUCTOS_TB.UNIDADES_ACTUALES%TYPE,
    P_ID_ESTADO          IN FIDE_PRODUCTOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PRODUCTOS_UPDATE (
    P_ID_PRODUCTO        IN FIDE_PRODUCTOS_TB.ID_PRODUCTO%TYPE,
    P_NOMBRE             IN FIDE_PRODUCTOS_TB.NOMBRE%TYPE,
    P_DESCRIPCION        IN FIDE_PRODUCTOS_TB.DESCRIPCION%TYPE,
    P_PRECIO             IN FIDE_PRODUCTOS_TB.PRECIO%TYPE,
    P_UNIDADES_ACTUALES  IN FIDE_PRODUCTOS_TB.UNIDADES_ACTUALES%TYPE,
    P_ID_ESTADO          IN FIDE_PRODUCTOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PRODUCTOS_DELETE (
    P_ID_PRODUCTO IN FIDE_PRODUCTOS_TB.ID_PRODUCTO%TYPE
);

--TABLA PRODUCTOS POR PROVEEDOR
--TABLA PRODUCTOS POR PROVEEDOR
--TABLA PRODUCTOS POR PROVEEDOR
PROCEDURE SP_FIDE_PRODUCTOS_X_PROVEEDOR_INSERT (
    P_ID_PRODUCTO  IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_PRODUCTO%TYPE,
    P_ID_PROVEEDOR IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_PROVEEDOR%TYPE,
    P_ID_ESTADO    IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PRODUCTOS_X_PROVEEDOR_UPDATE (
    P_ID_PRODUCTO  IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_PRODUCTO%TYPE,
    P_ID_PROVEEDOR IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_PROVEEDOR%TYPE,
    P_ID_ESTADO    IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PRODUCTOS_X_PROVEEDOR_DELETE (
    P_ID_PROVEEDOR IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_PROVEEDOR%TYPE,
    P_ID_PRODUCTO  IN FIDE_PRODUCTOS_X_PROVEEDOR_TB.ID_PRODUCTO%TYPE
);

--22. TABLA TIPOS DE PLAGAS
--22. TABLA TIPOS DE PLAGAS
--22. TABLA TIPOS DE PLAGAS
PROCEDURE SP_FIDE_PLAGAS_INSERT (
    P_ID_PLAGA            IN FIDE_PLAGAS_TB.ID_PLAGA%TYPE,
    P_TIPO                IN FIDE_PLAGAS_TB.TIPO%TYPE,
    P_NOMBRE              IN FIDE_PLAGAS_TB.NOMBRE%TYPE,
    P_DESCRIPCION         IN FIDE_PLAGAS_TB.DESCRIPCION%TYPE,
    P_UNIDADES_NECESARIAS IN FIDE_PLAGAS_TB.UNIDADES_NECESARIAS%TYPE,
    P_ID_ESTADO           IN FIDE_PLAGAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PLAGAS_UPDATE (
    P_ID_PLAGA            IN FIDE_PLAGAS_TB.ID_PLAGA%TYPE,
    P_TIPO                IN FIDE_PLAGAS_TB.TIPO%TYPE,
    P_NOMBRE              IN FIDE_PLAGAS_TB.NOMBRE%TYPE,
    P_DESCRIPCION         IN FIDE_PLAGAS_TB.DESCRIPCION%TYPE,
    P_UNIDADES_NECESARIAS IN FIDE_PLAGAS_TB.UNIDADES_NECESARIAS%TYPE,
    P_ID_ESTADO           IN FIDE_PLAGAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PLAGAS_DELETE (
    P_ID_PLAGA IN FIDE_PLAGAS_TB.ID_PLAGA%TYPE
);

--23. TABLA PRODUCTOS POR PLAGA
--23. TABLA PRODUCTOS POR PLAGA
--23. TABLA PRODUCTOS POR PLAGA
PROCEDURE SP_FIDE_PRODUCTOS_X_PLAGA_INSERT (
    P_ID_PLAGA    IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_PLAGA%TYPE,
    P_ID_PRODUCTO IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO   IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PRODUCTOS_X_PLAGA_UPDATE (
    P_ID_PLAGA    IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_PLAGA%TYPE,
    P_ID_PRODUCTO IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO   IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PRODUCTOS_X_PLAGA_DELETE (
    P_ID_PLAGA    IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_PLAGA%TYPE,
    P_ID_PRODUCTO IN FIDE_PRODUCTOS_X_PLAGA_TB.ID_PRODUCTO%TYPE
);

--24. TABLA SERVICIOS REALIZADOS
--24. TABLA SERVICIOS REALIZADOS
--24. TABLA SERVICIOS REALIZADOS
PROCEDURE SP_FIDE_SERVICIOS_REALIZADOS_INSERT (
    P_ID_SERVICIO_REALIZADO IN FIDE_SERVICIOS_REALIZADOS_TB.ID_SERVICIO_REALIZADO%TYPE,
    P_UBICACION             IN FIDE_SERVICIOS_REALIZADOS_TB.UBICACION%TYPE,
    P_INFORME               IN FIDE_SERVICIOS_REALIZADOS_TB.INFORME%TYPE,
    P_ID_ESTADO             IN FIDE_SERVICIOS_REALIZADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_SERVICIOS_REALIZADOS_UPDATE (
    P_ID_SERVICIO_REALIZADO IN FIDE_SERVICIOS_REALIZADOS_TB.ID_SERVICIO_REALIZADO%TYPE,
    P_UBICACION             IN FIDE_SERVICIOS_REALIZADOS_TB.UBICACION%TYPE,
    P_INFORME               IN FIDE_SERVICIOS_REALIZADOS_TB.INFORME%TYPE,
    P_ID_ESTADO             IN FIDE_SERVICIOS_REALIZADOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_SERVICIOS_REALIZADOS_DELETE (
    P_ID_SERVICIO_REALIZADO IN FIDE_SERVICIOS_REALIZADOS_TB.ID_SERVICIO_REALIZADO%TYPE
);

--25. TABLA SERVICIOS
--25. TABLA SERVICIOS
--25. TABLA SERVICIOS
PROCEDURE SP_FIDE_SERVICIOS_INSERT (
    P_ID_SERVICIO           IN FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
    P_NOMBRE                IN FIDE_SERVICIOS_TB.NOMBRE%TYPE,
    P_ID_PLAGA              IN FIDE_SERVICIOS_TB.ID_PLAGA%TYPE,
    P_ID_USUARIO            IN FIDE_SERVICIOS_TB.ID_USUARIO%TYPE,
    P_ID_SERVICIO_REALIZADO IN FIDE_SERVICIOS_TB.ID_SERVICIO_REALIZADO%TYPE,
    P_ID_ESTADO             IN FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_SERVICIOS_UPDATE (
    P_ID_SERVICIO           IN FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE,
    P_NOMBRE                IN FIDE_SERVICIOS_TB.NOMBRE%TYPE,
    P_ID_PLAGA              IN FIDE_SERVICIOS_TB.ID_PLAGA%TYPE,
    P_ID_USUARIO            IN FIDE_SERVICIOS_TB.ID_USUARIO%TYPE,
    P_ID_SERVICIO_REALIZADO IN FIDE_SERVICIOS_TB.ID_SERVICIO_REALIZADO%TYPE,
    P_ID_ESTADO             IN FIDE_SERVICIOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_SERVICIOS_DELETE (
    P_ID_SERVICIO IN FIDE_SERVICIOS_TB.ID_SERVICIO%TYPE
);

--26. TABLA CLIENTES POR SERVICIO
--26. TABLA CLIENTES POR SERVICIO
--26. TABLA CLIENTES POR SERVICIO
PROCEDURE SP_FIDE_CLIENTES_X_SERVICIO_INSERT (
    P_ID_CLIENTE  IN FIDE_CLIENTES_X_SERVICIO_TB.ID_CLIENTE%TYPE,
    P_ID_SERVICIO IN FIDE_CLIENTES_X_SERVICIO_TB.ID_SERVICIO%TYPE,
    P_ID_ESTADO   IN FIDE_CLIENTES_X_SERVICIO_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CLIENTES_X_SERVICIO_UPDATE (
    P_ID_CLIENTE  IN FIDE_CLIENTES_X_SERVICIO_TB.ID_CLIENTE%TYPE,
    P_ID_SERVICIO IN FIDE_CLIENTES_X_SERVICIO_TB.ID_SERVICIO%TYPE,
    P_ID_ESTADO   IN FIDE_CLIENTES_X_SERVICIO_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_CLIENTES_X_SERVICIO_DELETE (
    P_ID_CLIENTE  IN FIDE_CLIENTES_X_SERVICIO_TB.ID_CLIENTE%TYPE,
    P_ID_SERVICIO IN FIDE_CLIENTES_X_SERVICIO_TB.ID_SERVICIO%TYPE
);

--27. TABLA SUSCRIPCIONES
--27. TABLA SUSCRIPCIONES
--27. TABLA SUSCRIPCIONES
PROCEDURE SP_FIDE_SUSCRIPCIONES_INSERT (
    P_ID_SUSCRIPCION IN FIDE_SUSCRIPCIONES_TB.ID_SUSCRIPCION%TYPE,
    P_NOMBRE         IN FIDE_SUSCRIPCIONES_TB.NOMBRE%TYPE,
    P_ID_PAGO        IN FIDE_SUSCRIPCIONES_TB.ID_PAGO%TYPE,
    P_ID_ESTADO      IN FIDE_SUSCRIPCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_SUSCRIPCIONES_UPDATE (
    P_ID_SUSCRIPCION IN FIDE_SUSCRIPCIONES_TB.ID_SUSCRIPCION%TYPE,
    P_NOMBRE         IN FIDE_SUSCRIPCIONES_TB.NOMBRE%TYPE,
    P_ID_PAGO        IN FIDE_SUSCRIPCIONES_TB.ID_PAGO%TYPE,
    P_ID_ESTADO      IN FIDE_SUSCRIPCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_SUSCRIPCIONES_DELETE (
    P_ID_SUSCRIPCION IN FIDE_SUSCRIPCIONES_TB.ID_SUSCRIPCION%TYPE
);

--28. TABLA VISITAS
--28. TABLA VISITAS
--28. TABLA VISITAS
PROCEDURE SP_FIDE_VISITAS_INSERT (
    P_ID_VISITA      IN FIDE_VISITAS_TB.ID_VISITA%TYPE,
    P_NOMBRE         IN FIDE_VISITAS_TB.NOMBRE%TYPE,
    P_ID_SUSCRIPCION IN FIDE_VISITAS_TB.ID_SUSCRIPCION%TYPE,
    P_ID_CLIENTE     IN FIDE_VISITAS_TB.ID_CLIENTE%TYPE,
    P_ID_ESTADO      IN FIDE_VISITAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_VISITAS_UPDATE (
    P_ID_VISITA      IN FIDE_VISITAS_TB.ID_VISITA%TYPE,
    P_NOMBRE         IN FIDE_VISITAS_TB.NOMBRE%TYPE,
    P_ID_SUSCRIPCION IN FIDE_VISITAS_TB.ID_SUSCRIPCION%TYPE,
    P_ID_CLIENTE     IN FIDE_VISITAS_TB.ID_CLIENTE%TYPE,
    P_ID_ESTADO      IN FIDE_VISITAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_VISITAS_DELETE (
    P_ID_VISITA IN FIDE_VISITAS_TB.ID_VISITA%TYPE
);

--30. TABLA METODOS DE PAGO
--30. TABLA METODOS DE PAGO
--30. TABLA METODOS DE PAGO
PROCEDURE SP_FIDE_METODOSDEPAGO_INSERT (
    P_ID_METODO_PAGO IN FIDE_METODOSDEPAGO_TB.ID_METODO_PAGO%TYPE,
    P_NOMBRE         IN FIDE_METODOSDEPAGO_TB.NOMBRE%TYPE,
    P_ID_ESTADO      IN FIDE_METODOSDEPAGO_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_METODOSDEPAGO_UPDATE (
    P_ID_METODO_PAGO IN FIDE_METODOSDEPAGO_TB.ID_METODO_PAGO%TYPE,
    P_NOMBRE         IN FIDE_METODOSDEPAGO_TB.NOMBRE%TYPE,
    P_ID_ESTADO      IN FIDE_METODOSDEPAGO_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_METODOSDEPAGO_DELETE (
    P_ID_METODO_PAGO IN FIDE_METODOSDEPAGO_TB.ID_METODO_PAGO%TYPE
);

--31. TABLA PAGOS
--31. TABLA PAGOS
--31. TABLA PAGOS
PROCEDURE SP_FIDE_PAGOS_INSERT (
    P_ID_PAGO        IN FIDE_PAGOS_TB.ID_PAGO%TYPE,
    P_ID_METODO_PAGO IN FIDE_PAGOS_TB.ID_METODO_PAGO%TYPE,
    P_ID_ESTADO      IN FIDE_PAGOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PAGOS_UPDATE (
    P_ID_PAGO        IN FIDE_PAGOS_TB.ID_PAGO%TYPE,
    P_ID_METODO_PAGO IN FIDE_PAGOS_TB.ID_METODO_PAGO%TYPE,
    P_ID_ESTADO      IN FIDE_PAGOS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_PAGOS_DELETE (
    P_ID_PAGO IN FIDE_PAGOS_TB.ID_PAGO%TYPE
);

--32. TABLA DETALLE DE TRANSACCIONES
--32. TABLA DETALLE DE TRANSACCIONES
--32. TABLA DETALLE DE TRANSACCIONES
PROCEDURE SP_FIDE_DETALLE_TRANSACCIONES_INSERT (
    P_ID_DETALLE_TRANSACCION IN FIDE_DETALLE_TRANSACCIONES_TB.ID_DETALLE_TRANSACCION%TYPE,
    P_DETALLE                IN FIDE_DETALLE_TRANSACCIONES_TB.DETALLE%TYPE,
    P_ID_ESTADO              IN FIDE_DETALLE_TRANSACCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_DETALLE_TRANSACCIONES_UPDATE (
    P_ID_DETALLE_TRANSACCION IN FIDE_DETALLE_TRANSACCIONES_TB.ID_DETALLE_TRANSACCION%TYPE,
    P_DETALLE                IN FIDE_DETALLE_TRANSACCIONES_TB.DETALLE%TYPE,
    P_ID_ESTADO              IN FIDE_DETALLE_TRANSACCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_DETALLE_TRANSACCIONES_DELETE (
    P_ID_DETALLE_TRANSACCION IN FIDE_DETALLE_TRANSACCIONES_TB.ID_DETALLE_TRANSACCION%TYPE
);

--33. TABLA TRANSACCIONES
--33. TABLA TRANSACCIONES
--33. TABLA TRANSACCIONES
PROCEDURE SP_FIDE_TRANSACCIONES_INSERT (
    P_ID_TRANSACCION         IN FIDE_TRANSACCIONES_TB.ID_TRANSACCION%TYPE,
    P_ID_PAGO                IN FIDE_TRANSACCIONES_TB.ID_PAGO%TYPE,
    P_MONTO                  IN FIDE_TRANSACCIONES_TB.MONTO%TYPE,
    P_ID_DETALLE_TRANSACCION IN FIDE_TRANSACCIONES_TB.ID_DETALLE_TRANSACCION%TYPE,
    P_ID_ESTADO              IN FIDE_TRANSACCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TRANSACCIONES_UPDATE (
    P_ID_TRANSACCION         IN FIDE_TRANSACCIONES_TB.ID_TRANSACCION%TYPE,
    P_ID_PAGO                IN FIDE_TRANSACCIONES_TB.ID_PAGO%TYPE,
    P_MONTO                  IN FIDE_TRANSACCIONES_TB.MONTO%TYPE,
    P_ID_DETALLE_TRANSACCION IN FIDE_TRANSACCIONES_TB.ID_DETALLE_TRANSACCION%TYPE,
    P_ID_ESTADO              IN FIDE_TRANSACCIONES_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_TRANSACCIONES_DELETE (
    P_ID_TRANSACCION IN FIDE_TRANSACCIONES_TB.ID_TRANSACCION%TYPE
);

--34. TABLA FACTURAS
--34. TABLA FACTURAS
--34. TABLA FACTURAS
PROCEDURE SP_FIDE_FACTURAS_INSERT (
    P_ID_FACTURA     IN FIDE_FACTURAS_TB.ID_FACTURA%TYPE,
    P_NUMERO         IN FIDE_FACTURAS_TB.NUMERO%TYPE,
    P_TOTAL          IN FIDE_FACTURAS_TB.TOTAL%TYPE,
    P_ID_TRANSACCION IN FIDE_FACTURAS_TB.ID_TRANSACCION%TYPE,
    P_ID_ESTADO      IN FIDE_FACTURAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_FACTURAS_UPDATE (
    P_ID_FACTURA     IN FIDE_FACTURAS_TB.ID_FACTURA%TYPE,
    P_NUMERO         IN FIDE_FACTURAS_TB.NUMERO%TYPE,
    P_TOTAL          IN FIDE_FACTURAS_TB.TOTAL%TYPE,
    P_ID_TRANSACCION IN FIDE_FACTURAS_TB.ID_TRANSACCION%TYPE,
    P_ID_ESTADO      IN FIDE_FACTURAS_TB.ID_ESTADO%TYPE
);
PROCEDURE SP_FIDE_FACTURAS_DELETE (
    P_ID_FACTURA IN FIDE_FACTURAS_TB.ID_FACTURA%TYPE
);

--=====================================================
-- FUNCIONES CON CURSOR (AVANCE 2)
--=====================================================
--1. Nombre completo del cliente segun CLIENTE_ID
FUNCTION FIDE_NOMBRE_CLIENTE_CURSOR_FN(P_CLIENTE_ID NUMBER) RETURN VARCHAR2;

--2. Nombre completo del empleado segun EMPLEADO_ID
FUNCTION FIDE_NOMBRE_EMPLEADO_CURSOR_FN(P_EMPLEADO_ID NUMBER) RETURN VARCHAR2;

--3. Nombre del servicio segun SERVICIO_ID
FUNCTION FIDE_NOMBRE_SERVICIO_CURSOR_FN(P_SERVICIO_ID NUMBER) RETURN VARCHAR2;

--4. Plaga que trata un servicio segun SERVICIO_ID
FUNCTION FIDE_PLAGA_SERVICIO_CURSOR_FN(P_SERVICIO_ID NUMBER) RETURN VARCHAR2;

--5. Estado de una factura segun FACTURA_ID
FUNCTION FIDE_ESTADO_FACTURA_CURSOR_FN(P_FACTURA_ID NUMBER) RETURN VARCHAR2;

--6. Metodo de pago de una factura segun FACTURA_ID
FUNCTION FIDE_METODO_PAGO_FACTURA_CURSOR_FN(P_FACTURA_ID NUMBER) RETURN VARCHAR2;

--7. Cantidad de servicios contratados por un cliente (CLIENTE_ID)
FUNCTION FIDE_CANTIDAD_SERVICIOS_CLIENTE_CURSOR_FN(P_CLIENTE_ID NUMBER) RETURN NUMBER;

--8. Cantidad de productos de un proveedor (PROVEEDOR_ID)
FUNCTION FIDE_CANTIDAD_PRODUCTOS_PROVEEDOR_CURSOR_FN(P_PROVEEDOR_ID NUMBER) RETURN NUMBER;

--9. Cantidad de facturas de un cliente (CLIENTE_ID)
FUNCTION FIDE_CANTIDAD_FACTURAS_CLIENTE_CURSOR_FN(P_CLIENTE_ID NUMBER) RETURN NUMBER;

--10. Cantidad de pagos registrados de un cliente (CLIENTE_ID)
FUNCTION FIDE_CANTIDAD_PAGOS_CLIENTE_CURSOR_FN(P_CLIENTE_ID NUMBER) RETURN NUMBER;

--11. Total gastado por un cliente (CLIENTE_ID)
FUNCTION FIDE_TOTAL_GASTADO_CLIENTE_CURSOR_FN(P_CLIENTE_ID NUMBER) RETURN NUMBER;

--12. Producto con menor stock (sin parametros)
FUNCTION FIDE_PRODUCTO_MENOR_STOCK_CURSOR_FN RETURN NUMBER;

--13. Producto mas caro (sin parametros)
FUNCTION FIDE_PRODUCTO_MAS_CARO_CURSOR_FN RETURN NUMBER;

--14. Cliente que mas ha gastado (sin parametros)
FUNCTION FIDE_CLIENTE_MAS_GASTADO_CURSOR_FN RETURN NUMBER;

--15. Proveedor con mas productos (sin parametros)
FUNCTION FIDE_PROVEEDOR_MAS_PRODUCTOS_CURSOR_FN RETURN NUMBER;

END FIDE_PROYECTO_FINAL_PKG;

/
