

/*=========================================================
SCRIPT PARA ELIMINAR TABLAS (ORDEN DE DEPENDENCIAS)
=========================================================*/
/*
-- 1. Grupo Facturación, Transacciones y Pagos
DROP TABLE FIDE_FACTURAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TRANSACCIONES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PAGOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DETALLE_TRANSACCIONES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_METODOSDEPAGO_TB CASCADE CONSTRAINTS;
/

-- 2. Grupo Visitas y Suscripciones
DROP TABLE FIDE_VISITAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_SUSCRIPCIONES_TB CASCADE CONSTRAINTS;
/

-- 3. Grupo Servicios y Plagas
DROP TABLE FIDE_CLIENTES_X_SERVICIO_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_SERVICIOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_SERVICIOS_REALIZADOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PRODUCTOS_X_PLAGA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PLAGAS_TB CASCADE CONSTRAINTS;
/

-- 4. Grupo Productos y Proveedores
DROP TABLE FIDE_PRODUCTOS_X_PROVEEDOR_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PRODUCTOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CORREOS_PROVEEDORES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TELEFONOS_PROVEEDORES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVEEDORES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_REABASTECIMIENTO_INVENTARIO_TB CASCADE CONSTRAINTS;
/

-- 5. Grupo Usuarios, Roles y Permisos
DROP TABLE FIDE_USUARIOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PERMISOS_X_ROL_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PERMISOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_ROLES_TB CASCADE CONSTRAINTS;
/

-- 6. Grupo Empleados
DROP TABLE FIDE_CORREOS_EMPLEADOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TELEFONOS_EMPLEADOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_EMPLEADOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PUESTOS_TB CASCADE CONSTRAINTS;
/

-- 7. Grupo Clientes y Ubicaciones Geográficas
DROP TABLE FIDE_DIRECCIONES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DISTRITOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CANTONES_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_PROVINCIAS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CORREOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_TELEFONOS_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_CLIENTES_TB CASCADE CONSTRAINTS;
/

-- 8. Tabla Base General (Padre de todas)
DROP TABLE FIDE_ESTADOS_TB CASCADE CONSTRAINTS;
/
*/


/*=========================================================
1. TABLA DE ESTADOS
=========================================================*/
CREATE TABLE FIDE_ESTADOS_TB (
    ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADOS_TB_ID_ESTADO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(100)
);
/
/*=========================================================
2. TABLA DE CLIENTES
=========================================================*/
CREATE TABLE FIDE_CLIENTES_TB(
    ID_CLIENTE NUMBER CONSTRAINT FIDE_CLIENTES_ID_CLIENTE_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CLIENTES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
3. TABLA DE TELEFONOS
=========================================================*/
CREATE TABLE FIDE_TELEFONOS_TB(
    ID_CLIENTE NUMBER,
    TELEFONO VARCHAR2(20),
    TIPO VARCHAR2(30),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TELEFONOS_ID_CLIENTE_TELEFONO_PK PRIMARY KEY (ID_CLIENTE, TELEFONO),
    CONSTRAINT FIDE_TELEFONOS_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
    CONSTRAINT FIDE_TELEFONOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
4. TABLA DE CORREOS
=========================================================*/
CREATE TABLE FIDE_CORREOS_TB(
    ID_CLIENTE NUMBER,
    CORREO VARCHAR2(200),
    TIPO VARCHAR2(30),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CORREOS_ID_CLIENTE_CORREO_PK PRIMARY KEY (ID_CLIENTE, CORREO),
    CONSTRAINT FIDE_CORREOS_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
    CONSTRAINT FIDE_CORREOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
5. TABLA DE PROVINCIAS
=========================================================*/
CREATE TABLE FIDE_PROVINCIAS_TB(
    ID_PROVINCIA NUMBER CONSTRAINT FIDE_PROVINCIAS_ID_PROVINCIA_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PROVINCIAS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)

);
/
/*=========================================================
6. TABLA DE CANTONES
=========================================================*/
CREATE TABLE FIDE_CANTONES_TB(
    ID_CANTON NUMBER CONSTRAINT FIDE_CANTONES_ID_CANTON_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CANTONES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
7. TABLA DE DISTRITOS
=========================================================*/
CREATE TABLE FIDE_DISTRITOS_TB(
    ID_DISTRITO NUMBER CONSTRAINT FIDE_DISTRITOS_ID_DISTRITO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_DISTRITOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
8. TABLA DE DIRECCIONES
=========================================================*/
CREATE TABLE FIDE_DIRECCIONES_TB(
    ID_CLIENTE NUMBER,
    ID_PROVINCIA NUMBER,
    ID_CANTON NUMBER,
    ID_DISTRITO NUMBER,
    ID_ESTADO NUMBER,
-- Preguntar nomenclatura de este PK
    CONSTRAINT FIDE_DIRECCIONES_PK PRIMARY KEY (ID_CLIENTE, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
    CONSTRAINT FIDE_DIRECCIONES_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_PROVINCIAS_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCIONES_CANTON_FK FOREIGN KEY (ID_CANTON) REFERENCES FIDE_CANTONES_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCIONES_DISTRITO_FK FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_DISTRITOS_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCIONES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
9. TABLA DE PUESTOS
=========================================================*/
CREATE TABLE FIDE_PUESTOS_TB(
    ID_PUESTO NUMBER CONSTRAINT FIDE_PUESTOS_ID_PUESTO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PUESTOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
10. TABLA DE EMPLEADOS
=========================================================*/
CREATE TABLE FIDE_EMPLEADOS_TB(
    ID_EMPLEADO NUMBER CONSTRAINT FIDE_EMPLEADOS_ID_EMPLEADO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP,
	ID_PUESTO NUMBER,
    ID_ESTADO NUMBER,	
	CONSTRAINT FIDE_EMPLEADOS_PUESTO_FK FOREIGN KEY (ID_PUESTO) REFERENCES FIDE_PUESTOS_TB(ID_PUESTO),
    CONSTRAINT FIDE_EMPLEADOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
11. TABLA DE TELEFONOS DE EMPLEADOS
=========================================================*/
CREATE TABLE FIDE_TELEFONOS_EMPLEADOS_TB(
    ID_EMPLEADO NUMBER,
    TELEFONO VARCHAR2(20),
    TIPO VARCHAR2(30),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TELEFONOS_EMPLEADOS_ID_EMPLEADO_TELEFONO_PK PRIMARY KEY (ID_EMPLEADO, TELEFONO),
    CONSTRAINT FIDE_TELEFONOS_EMPLEADOS_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADOS_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_TELEFONOS_EMPLEADOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
12. TABLA DE CORREOS DE EMPLEADOS
=========================================================*/
CREATE TABLE FIDE_CORREOS_EMPLEADOS_TB(
    ID_EMPLEADO NUMBER,
    CORREO VARCHAR2(200),
    TIPO VARCHAR2(30),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CORREOS_EMPLEADOS_ID_EMPLEADO_CORREO_PK PRIMARY KEY (ID_EMPLEADO, CORREO),
    CONSTRAINT FIDE_CORREOS_EMPLEADOS_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADOS_TB(ID_EMPLEADO),
    CONSTRAINT FIDE_CORREOS_EMPLEADOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
13. TABLA DE ROLES
=========================================================*/
CREATE TABLE FIDE_ROLES_TB(
    ID_ROL NUMBER CONSTRAINT FIDE_ROLES_ID_ROL_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_ROLES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
14. TABLA DE PERMISOS
=========================================================*/
CREATE TABLE FIDE_PERMISOS_TB(
    ID_PERMISO NUMBER CONSTRAINT FIDE_PERMISOS_ID_PERMISO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PERMISOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
15. TABLA DE PERMISOS POR ROL
=========================================================*/
CREATE TABLE FIDE_PERMISOS_X_ROL_TB(
    ID_ROL NUMBER,
    ID_PERMISO NUMBER,    
	ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PERMISOS_X_ROL_ID_ROL_ID_PERMISO_PK PRIMARY KEY (ID_ROL, ID_PERMISO),
    CONSTRAINT FIDE_PERMISOS_X_ROL_ROL_FK FOREIGN KEY (ID_ROL) REFERENCES FIDE_ROLES_TB(ID_ROL),
    CONSTRAINT FIDE_PERMISOS_X_ROL_PERMISO_FK FOREIGN KEY (ID_PERMISO) REFERENCES FIDE_PERMISOS_TB(ID_PERMISO),
	CONSTRAINT FIDE_PERMISOS_X_ROL_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
16. TABLA DE USUARIOS
=========================================================*/
CREATE TABLE FIDE_USUARIOS_TB(
    ID_USUARIO NUMBER CONSTRAINT FIDE_USUARIOS_ID_USUARIO_PK PRIMARY KEY,
	USUARIO VARCHAR2(20),
    CONTRASEÑA VARCHAR2(20),
    ID_EMPLEADO NUMBER,
    ID_ROL NUMBER,
	ID_ESTADO NUMBER,
    CONSTRAINT FIDE_USUARIOS_EMPLEADOS_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_EMPLEADOS_TB(ID_EMPLEADO),
	CONSTRAINT FIDE_USUARIOS_ROL_FK FOREIGN KEY (ID_ROL) REFERENCES FIDE_ROLES_TB(ID_ROL),
    CONSTRAINT FIDE_USUARIOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
-- AGREGAR VINCULO ENTRE USUARIOS Y CLIENTES (login de clientes) --
ALTER TABLE FIDE_USUARIOS_TB
ADD ID_CLIENTE NUMBER;

ALTER TABLE FIDE_USUARIOS_TB
ADD CONSTRAINT FIDE_USUARIOS_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE);

-- UN USUARIO ES O EMPLEADO O CLIENTE, NUNCA AMBOS --
ALTER TABLE FIDE_USUARIOS_TB
ADD CONSTRAINT FIDE_USUARIOS_DUENO_CHK CHECK (
    (ID_EMPLEADO IS NOT NULL AND ID_CLIENTE IS NULL) OR
    (ID_EMPLEADO IS NULL AND ID_CLIENTE IS NOT NULL)
);

-- RENOMBRAR CONTRASEÑA A CONTRASENA (evita problemas de codificacion de la Ñ entre Mac y Windows) --
ALTER TABLE FIDE_USUARIOS_TB RENAME COLUMN CONTRASEÑA TO CONTRASENA;

/*=========================================================
17. TABLA DE REABASTECIMIENTO DE INVENTARIO
=========================================================*/
CREATE TABLE FIDE_REABASTECIMIENTO_INVENTARIO_TB(
    ID_REABASTECIMIENTO NUMBER  CONSTRAINT FIDE_REABASTECIMIENTO_INVENTARIO_ID_REABASTECIMIENTO_PK PRIMARY KEY,
    CANTIDAD NUMBER,
    FECHA_LLEGADA TIMESTAMP DEFAULT SYSTIMESTAMP,
    ID_ESTADO NUMBER,    
    CONSTRAINT FIDE_REABASTECIMIENTO_INVENTARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
18. TABLA DE PROVEEDORES
=========================================================*/
CREATE TABLE FIDE_PROVEEDORES_TB(
    ID_PROVEEDOR NUMBER CONSTRAINT FIDE_PROVEEDORES_ID_PROVEEDOR_PK PRIMARY KEY,
	NOMBRE VARCHAR2(100),
    ID_REABASTECIMIENTO NUMBER,
    ID_ESTADO NUMBER,   
    CONSTRAINT FIDE_PROVEEDORES_REABASTECIMIENTO_FK FOREIGN KEY (ID_REABASTECIMIENTO) REFERENCES FIDE_REABASTECIMIENTO_INVENTARIO_TB(ID_REABASTECIMIENTO),
    CONSTRAINT FIDE_PROVEEDORES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
19 TABLA DE TELEFONOS DE PROVEEDORES
=========================================================*/
CREATE TABLE FIDE_TELEFONOS_PROVEEDORES_TB(
    ID_PROVEEDOR NUMBER,
    TELEFONO VARCHAR2(20),
    TIPO VARCHAR2(30),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TELEFONOS_PROVEEDORES_ID_PROVEEDOR_TELEFONO_PK PRIMARY KEY (ID_PROVEEDOR, TELEFONO),
    CONSTRAINT FIDE_TELEFONOS_PROVEEDORES_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDORES_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_TELEFONOS_PROVEEDORES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
20 TABLA DE CORREOS DE PROVEEDORES
=========================================================*/
CREATE TABLE FIDE_CORREOS_PROVEEDORES_TB(
    ID_PROVEEDOR NUMBER,
    CORREO VARCHAR2(200),
    TIPO VARCHAR2(30),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CORREOS_PROVEEDORES_ID_PROVEEDOR_CORREO_PK PRIMARY KEY (ID_PROVEEDOR, CORREO),
    CONSTRAINT FIDE_CORREOS_PROVEEDORES_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDORES_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_CORREOS_PROVEEDORES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
21. TABLA DE PRODUCTOS
=========================================================*/
CREATE TABLE FIDE_PRODUCTOS_TB(
    ID_PRODUCTO NUMBER CONSTRAINT FIDE_PRODUCTOS_ID_PRODUCTO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    PRECIO NUMBER(10,2) NOT NULL,
    UNIDADES_ACTUALES NUMBER NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PRODUCTOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
22. TABLA DE PRODUCTOS POR PROVEEDOR
=========================================================*/
CREATE TABLE FIDE_PRODUCTOS_X_PROVEEDOR_TB(
    ID_PRODUCTO NUMBER, 
	ID_PROVEEDOR NUMBER,
	ID_ESTADO NUMBER,	
    CONSTRAINT FIDE_PRODUCTOS_X_PROVEEDOR_ID_PRODUCTO_ID_PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR, ID_PRODUCTO),
	CONSTRAINT FIDE_PRODUCTOS_X_PROVEEDOR_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_PRODUCTOS_X_PROVEEDOR_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES FIDE_PROVEEDORES_TB(ID_PROVEEDOR),
    CONSTRAINT FIDE_PRODUCTOS_X_PROVEEDOR_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
23.TABLA DE TIPOS DE PLAGAS
=========================================================*/
CREATE TABLE FIDE_PLAGAS_TB(
    ID_PLAGA NUMBER CONSTRAINT FIDE_PLAGAS_ID_PLAGA_PK PRIMARY KEY,
	TIPO VARCHAR2(30),
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    UNIDADES_NECESARIAS NUMBER NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PLAGAS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
24. TABLA DE PRODUCTOS POR PLAGA
=========================================================*/
CREATE TABLE FIDE_PRODUCTOS_X_PLAGA_TB(
    ID_PLAGA NUMBER, 
	ID_PRODUCTO NUMBER,
	ID_ESTADO NUMBER,	
    CONSTRAINT FIDE_PRODUCTOS_X_PLAGA_ID_PLAGA_ID_PRODUCTO_PK PRIMARY KEY (ID_PLAGA, ID_PRODUCTO),  
	CONSTRAINT FIDE_PRODUCTOS_X_PLAGA_PLAGA_FK FOREIGN KEY (ID_PLAGA) REFERENCES FIDE_PLAGAS_TB(ID_PLAGA),
	CONSTRAINT FIDE_PRODUCTOS_X_PLAGA_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO),
	CONSTRAINT FIDE_PRODUCTOS_X_PLAGA_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/*=========================================================
25. TABLA DE SERVICIOS REALIZADOS
=========================================================*/
CREATE TABLE FIDE_SERVICIOS_REALIZADOS_TB(
    ID_SERVICIO_REALIZADO NUMBER CONSTRAINT FIDE_SERVICIOS_REALIZADOS_ID_SERVICIO_REALIZADO_PK PRIMARY KEY,
	FECHA TIMESTAMP DEFAULT SYSTIMESTAMP,
	UBICACION VARCHAR2(100), 
	INFORME VARCHAR2(1000), 
	ID_ESTADO NUMBER,	
	CONSTRAINT FIDE_SERVICIOS_REALIZADOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
26. TABLA DE SERVICIOS
=========================================================*/
CREATE TABLE FIDE_SERVICIOS_TB(
    ID_SERVICIO NUMBER CONSTRAINT FIDE_SERVICIOS_ID_SERVICIO_PK PRIMARY KEY,
	NOMBRE VARCHAR2(100) NOT NULL,
	ID_PLAGA NUMBER, 
	ID_USUARIO NUMBER, 
	ID_SERVICIO_REALIZADO NUMBER,
	ID_ESTADO NUMBER,
	CONSTRAINT FIDE_SERVICIOS_PLAGA_FK FOREIGN KEY (ID_PLAGA) REFERENCES FIDE_PLAGAS_TB(ID_PLAGA),
	CONSTRAINT FIDE_SERVICIOS_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES FIDE_USUARIOS_TB(ID_USUARIO),
	CONSTRAINT FIDE_SERVICIOS_SERVICIO_REALIZADO_FK FOREIGN KEY (ID_SERVICIO_REALIZADO) REFERENCES FIDE_SERVICIOS_REALIZADOS_TB(ID_SERVICIO_REALIZADO),	
	CONSTRAINT FIDE_SERVICIOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
27. TABLA DE CLIENTES POR SERVICIO
=========================================================*/
CREATE TABLE FIDE_CLIENTES_X_SERVICIO_TB(
    ID_CLIENTE NUMBER, 
	ID_SERVICIO NUMBER,
	ID_ESTADO NUMBER,	
    CONSTRAINT FIDE_CLIENTES_X_SERVICIO_ID_CLIENTE_ID_SERVICIO_PK PRIMARY KEY (ID_CLIENTE, ID_SERVICIO),  
	CONSTRAINT FIDE_CLIENTES_X_SERVICIO_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
	CONSTRAINT FIDE_CLIENTES_X_SERVICIO_SERVICIO_FK FOREIGN KEY (ID_SERVICIO) REFERENCES FIDE_SERVICIOS_TB(ID_SERVICIO),
	CONSTRAINT FIDE_CLIENTES_X_SERVICIO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
28. TABLA DE SUSCRIPCIONES
=========================================================*/
CREATE TABLE FIDE_SUSCRIPCIONES_TB(
    ID_SUSCRIPCION NUMBER CONSTRAINT FIDE_SUSCRIPCIONES_ID_SUSCRIPCIONES_PK PRIMARY KEY,
	NOMBRE VARCHAR2(100) NOT NULL,
	FECHA_INICIO TIMESTAMP DEFAULT SYSTIMESTAMP,
	FECHA_FIN TIMESTAMP DEFAULT SYSTIMESTAMP,
	ID_PAGO NUMBER,
	ID_ESTADO NUMBER,	
	CONSTRAINT FIDE_SUSCRIPCIONES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
29. TABLA DE VISITAS
=========================================================*/
CREATE TABLE FIDE_VISITAS_TB(
    ID_VISITA NUMBER CONSTRAINT FIDE_VISITAS_ID_VISITA_PK PRIMARY KEY,
	NOMBRE VARCHAR2(100) NOT NULL,
	FECHA_PROGRAMADA TIMESTAMP DEFAULT SYSTIMESTAMP,
	FECHA_REALIZADA TIMESTAMP DEFAULT SYSTIMESTAMP,
	ID_SUSCRIPCION NUMBER,
	ID_CLIENTE NUMBER,
	ID_ESTADO NUMBER,
	CONSTRAINT FIDE_VISITAS_SUSCRIPCION_FK FOREIGN KEY (ID_SUSCRIPCION) REFERENCES FIDE_SUSCRIPCIONES_TB(ID_SUSCRIPCION),	
	CONSTRAINT FIDE_VISITAS_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_CLIENTES_TB(ID_CLIENTE),
	CONSTRAINT FIDE_VISITAS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
30. TABLA DE METODOS DE PAGO 
=========================================================*/
CREATE TABLE FIDE_METODOSDEPAGO_TB(
    ID_METODO_PAGO NUMBER CONSTRAINT FIDE_METODOSDEPAGO_ID_METODO_PAGO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_METODOSDEPAGO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=======================================================
31. TABLA DE PAGOS
=========================================================*/
CREATE TABLE FIDE_PAGOS_TB(
    ID_PAGO NUMBER CONSTRAINT FIDE_PAGOS_ID_PAGO_PK PRIMARY KEY,
    FECHA TIMESTAMP DEFAULT SYSTIMESTAMP,
    ID_METODO_PAGO NUMBER,
    ID_ESTADO NUMBER,    
    CONSTRAINT FIDE_PAGOS_METODO_FK FOREIGN KEY (ID_METODO_PAGO) REFERENCES FIDE_METODOSDEPAGO_TB(ID_METODO_PAGO),
    CONSTRAINT FIDE_PAGOS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
/*=========================================================
32. TABLA DE DETALLE DE TRANSACCIONES
=========================================================*/
CREATE TABLE FIDE_DETALLE_TRANSACCIONES_TB(
    ID_DETALLE_TRANSACCION NUMBER CONSTRAINT FIDE_DETALLE_TRANSACCIONES_ID_DETALLE_TRANSACCION_PK PRIMARY KEY,
	DETALLE VARCHAR2(100),
	ID_ESTADO NUMBER,
	CONSTRAINT FIDE_DETALLE_TRANSACCIONES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/*=========================================================
33. TABLA DE TRANSACCIONES
=========================================================*/
CREATE TABLE FIDE_TRANSACCIONES_TB(
    ID_TRANSACCION NUMBER CONSTRAINT FIDE_TRANSACCIONES_ID_TRANSACCION_PK PRIMARY KEY,
	ID_PAGO NUMBER,
	MONTO NUMBER(10,2),
	FECHA TIMESTAMP DEFAULT SYSTIMESTAMP,
	ID_DETALLE_TRANSACCION NUMBER,
	ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TRANSACCIONES_PAGO_FK FOREIGN KEY (ID_PAGO) REFERENCES FIDE_PAGOS_TB(ID_PAGO),
	CONSTRAINT FIDE_TRANSACCIONES_DETALLE_TRANSACCION_FK FOREIGN KEY (ID_DETALLE_TRANSACCION) REFERENCES FIDE_DETALLE_TRANSACCIONES_TB(ID_DETALLE_TRANSACCION),
	CONSTRAINT FIDE_TRANSACCIONES_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/*=========================================================
34. TABLA DE FACTURAS
=========================================================*/
CREATE TABLE FIDE_FACTURAS_TB(
    ID_FACTURA NUMBER CONSTRAINT FIDE_FACTURAS_ID_FACTURA_PK PRIMARY KEY,
	NUMERO NUMBER,
	FECHA TIMESTAMP DEFAULT SYSTIMESTAMP,
	TOTAL NUMBER(10,2),
	ID_TRANSACCION NUMBER,
	ID_ESTADO NUMBER,
	CONSTRAINT FIDE_FACTURAS_TRANSACCION_FK FOREIGN KEY (ID_TRANSACCION) REFERENCES FIDE_TRANSACCIONES_TB(ID_TRANSACCION),
	CONSTRAINT FIDE_FACTURAS_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);