SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_NOMBRE_CLIENTE_CURSOR_FN(1) AS NOMBRE_CLIENTE FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_NOMBRE_EMPLEADO_CURSOR_FN(1) AS NOMBRE_EMPLEADO FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_NOMBRE_SERVICIO_CURSOR_FN(1) AS NOMBRE_SERVICIO FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_PLAGA_SERVICIO_CURSOR_FN(1) AS PLAGA_DEL_SERVICIO FROM DUAL;

SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADO_FACTURA_CURSOR_FN(1) AS ESTADO_FACTURA FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_METODO_PAGO_FACTURA_CURSOR_FN(1) AS METODO_PAGO FROM DUAL;

SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_CANTIDAD_SERVICIOS_CLIENTE_CURSOR_FN(1) AS CANTIDAD_SERVICIOS FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_CANTIDAD_PRODUCTOS_PROVEEDOR_CURSOR_FN(1) AS CANTIDAD_PRODUCTOS FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_CANTIDAD_FACTURAS_CLIENTE_CURSOR_FN(1) AS CANTIDAD_FACTURAS FROM DUAL;



SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_CANTIDAD_PAGOS_CLIENTE_CURSOR_FN(1) AS CANTIDAD_PAGOS FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_TOTAL_GASTADO_CLIENTE_CURSOR_FN(1) AS TOTAL_GASTADO FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_PRODUCTO_MENOR_STOCK_CURSOR_FN() AS PRODUCTO_MENOR_STOCK FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_PRODUCTO_MAS_CARO_CURSOR_FN() AS PRODUCTO_MAS_CARO FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTE_MAS_GASTADO_CURSOR_FN() AS CLIENTE_MAS_GASTADO FROM DUAL;


SELECT FIDE_PROYECTO_FINAL_PKG.FIDE_PROVEEDOR_MAS_PRODUCTOS_CURSOR_FN() AS PROVEEDOR_MAS_PRODUCTOS FROM DUAL;
